# Generated by Django 5.1.6 on 2025-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macapp', '0003_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
    ]
