# Generated by Django 5.1.6 on 2025-02-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macapp', '0004_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('image', models.ImageField(blank=True, upload_to='product_images/', verbose_name='Image')),
                ('price', models.IntegerField(verbose_name='Item Price')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Product Description')),
            ],
        ),
    ]
