# Generated by Django 5.1.6 on 2025-02-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macapp', '0005_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Quantity in Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
